### ISSUE TITLE
suggestions for gamma_direct

### ISSUE THREAD

**Issue by petigura** [jvanzand/trends#8]
use float multiplication

![image](https://user-images.githubusercontent.com/694371/122098864-37e67180-cdc6-11eb-9144-e3c4949453de.png)

use libc functions, not numpy

![image](https://user-images.githubusercontent.com/694371/122098956-5187b900-cdc6-11eb-93ed-338016921b31.png)

no need to compute `(1/100) * (24*3600)` at every iteration

![image](https://user-images.githubusercontent.com/694371/122099038-68c6a680-cdc6-11eb-9455-783a74a04ed1.png)

do not recompute things like cos(E). compute them once if you need and store them as temp variable. ### 

![image](https://user-images.githubusercontent.com/694371/122099196-96abeb00-cdc6-11eb-8863-400d61f14663.png)

**Comment by jvanzand** [comment]
• Testing out changes. Base run time is 0.007 s with 1e4 points
• "Use float multiplication"
◦ I was unsure of what was meant here. Use for-loops to multiply Mj and a by M_jup and au?
◦ I tried using loops to create these arrays, but it seems to have made things slower (0.021 without vs. 0.023 with). Also I sometimes get a division by 0 error.

• “Use libc functions, not numpy”: Does not seem to help
◦ First, I have to move to a for-loop because libc trig functions don’t support array arithmetic
◦ After putting in the loop and declaring all the new floats that are created in the loop, the run time is ~0.017, > 2x the base run time with numpy

• “No need to recompute (1/100)*(24/3600) at every iteration”
◦ Changed this, slight improvement

• “Do not recompute things like cos(E). Compute them once if you need and store them as temp variable.”
◦ Here are the occurrences of trig functions in gamma_direct:
• tan(E/2)
• cos(E)    x 7
• tan(nu/2)
• cos(E/2)
• sin(i)
• cos(nu) x2
• sin(nu + om) x2
• sin(E)  x2
• sin(nu)
• cos(nu+om)
◦ I only defined as variables those that appeared more than once
◦ I think there's a slight improvement here, but declaring the arrays makes the code a bit slower

**Comment by petigura** [comment]
"◦ After putting in the loop and declaring all the new floats that are created in the loop, the run time is ~0.017, > 2x the base run time with numpy"

i believe this will improve when you address #11

**Comment by petigura** [comment]
"• "Use float multiplication" -> see #9

**Comment by jvanzand** [comment]
Closing after addressing #9 and #11
